### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by christopherkullenberg** [computermacgyver/twitter-python#4]
First of all, thanks for sharing this software. 

I have collected twitter data for 500+ days now and I am beginning to start analyzing the data. However, when I try to decode the json files, every tenth or so file runs into a JSONDecodeError, for example: 

    JSONDecodeError: Expecting ',' delimiter: line 1 column 4171 (char 4170)

This occurs both in python 2 and 3, and with both the ``json`` and ``simplejson`` parsers. I have used some json-validators around the web, and it seems like the json is valid. This problem also occurs with the ``data2spreadsheet.py `` script.

I can't seem to get this error to disappear. Any ideas?

**Comment by computermacgyver** [comment]
Hi Christopher, Strange that the json/simplejson parsers don't work but json validators think it is fine. Was the data collected using the streaming api or the search/rest api? If you can write me with the [contact form on my website](http://www.scotthale.net/blog/?page_id=9) we might carry on by email and perhaps look at one of the files that is producing this error.

**Comment by christopherkullenberg** [comment]
Hi, I checked the error against my whole dataset. In over 300k tweets (collected with the streaming API), there were only about 200 errors. For my current project, that is not really a problem, and perhaps they were generated server-side rather than by your program. 

They errors seem to be quite random. I will send the json-output for these 200 tweets to you via e-mail, and perhaps you can find something in there. But, since the error is so infrequent, I am happy with the result anyway.

**Comment by computermacgyver** [comment]
Great. I'm going to close the issue here, but do feel free to follow up by email.
