### ISSUE TITLE
How to create new columns from JSON file?

### ISSUE THREAD

**Issue by ergosumdre** [computermacgyver/twitter-python#8]

**Comment by computermacgyver** [comment]
You can adjust the `csv_header` and `csvRow` methods in [data2spreadsheet.py](https://github.com/computermacgyver/twitter-python/blob/master/data2spreadsheet.py#L35)

**Comment by ergosumdre** [comment]
Thank you for the reply. I experience this error while parsing the field retweet url
`File "data2spreadsheet.py", line 125, in parse
    if json["retweeted_status"]["entities"]["urls"]["expanded_url"] else ""
TypeError: list indices must be integers or slices, not str
`
